# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ...

Parameters:
  DataBucketName:
    Type: String
# PyWrenFunctionName:
#   Type: String
#   Default: PyWrenFunction
# PyWrenRoleName:
#   Type: String
#   Default: PyWrenRole
  PyWrenBucketName:
    Type: String
  PyWrenRuntimeBucketName:
    Type: String
    Default: "pywren-runtimes-public-us-west-2"
# AmznFcastPipelineBucketName:
#   Type: String
#   Default: amznfcast-pipeline

Globals:
  Function:
    Timeout: 900
    MemorySize: 3008

Resources:
  EngineForecastFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !GetAtt EngineForecastRole.Arn

  EngineForecastRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: EngineForecastRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: ["lambda.amazonaws.com"]
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "EngineForecastRole-LambdaPolicy0"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ""
                Effect: Allow
                Action:
                  - lambda:*
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:*"
        - PolicyName: "EngineForecastRole-S3Policy0"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ""
                Effect: Allow
                Action:
                  - s3:List*
                  - s3:Put*
                  - s3:Get*
                  - s3:MultipartUpload*
                Resource:
                  - !Sub "arn:aws:s3:::${DataBucketName}"
                  - !Sub "arn:aws:s3:::${DataBucketName}/*"
                  - !Sub "arn:aws:s3:::${PyWrenBucketName}"
                  - !Sub "arn:aws:s3:::${PyWrenBucketName}/*"
        - PolicyName: "EngineForecastRole-S3policy1"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ""
                Effect: Allow
                Action:
                  - s3:List*
                  - s3:Get*
                Resource:
                  - !Sub "arn:aws:s3:::${PyWrenRuntimeBucketName}"
                  - !Sub "arn:aws:s3:::${PyWrenRuntimeBucketName}/*"
        - PolicyName: "EngineForecastRole-LogsPolicy1"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ""
                Effect: Allow
                Action:
                  - logs:*
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

# PyWrenFunction:
#   Type: AWS::Serverless::Application
#   Properties:
#     Location: ../voyager-pywren/template.yaml
#     Parameters:
#       PyWrenFunctionName: !Ref PyWrenFunctionName
#       PyWrenBucketName: !Ref PyWrenBucketName
#       PyWrenRuntimeBucketName: !Ref PyWrenRuntimeBucketName
#       PyWrenRoleName: !Ref PyWrenRoleName

# AmznFcastPipeline:
#   Type: AWS::Serverless::Application
#   Properties:
#     Location: ./amznfcast/template.yaml
#     Parameters:
#       AmznFcastPipelineBucketName: !Ref AmznFcastPipelineBucketName
